# Generated by Django 2.1.4 on 2019-01-12 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='participant',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='question',
            name='participants',
            field=models.ManyToManyField(related_name='questions_tried', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='solved_by',
            field=models.ManyToManyField(related_name='questions_solved', to=settings.AUTH_USER_MODEL),
        ),
    ]
