# Generated by Django 2.1.4 on 2018-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='platform',
            field=models.CharField(choices=[('HR', 'hacker_rank'), ('CC', 'code_chef')], max_length=10),
        ),
    ]
