# Generated by Django 2.1.4 on 2019-01-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
