# Generated by Django 2.1.4 on 2019-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingcenter', '0002_auto_20190110_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
