# Generated by Django 2.1.4 on 2019-01-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingcenter', '0003_auto_20190103_0843'),
        ('codingcenter', '0002_auto_20190111_2116'),
    ]

    operations = [
    ]
