from .assignment_views import AssignmentDetailView,AssignmentListView,AssignmentQuestionsView, AssignmentJoinView
from .question_views import QuestionDetailView, QuestionListView
from .user_views import AdminUserView, UserListView, UserDetailView
from .college_views import CollegeListView